## Rivers to be considered:
1. Beas
2. Satluj
3. Ganga
4. Brahmaputra
5. Cauvery
6. Godavari
7. Krishna
8. Mahanadi
9. Yamuna

In [125]:
from enum import Enum

import numpy as np
import pandas as pd

River = Enum(
    "River",
    [
        "YAMUNA",
        "SATLUJ",
        "BEAS",
        "GANGA",
        "MAHANADI",
        "BRAHMAPUTRA",
        "GODAVARI",
        "KRISHNA",
        "CAUVERY",
    ],
)


cols = [
    "CODE",
    "LOCATION",
    "STATE",
    "T_MIN",
    "T_MAX",
    "T_AVG",
    "DO_MIN",
    "DO_MAX",
    "DO_AVG",
    "PH_MIN",
    "PH_MAX",
    "PH_AVG",
    "COND_MIN",
    "COND_MAX",
    "COND_AVG",
    "BOD_MIN",
    "BOD_MAX",
    "BOD_AVG",
    "N_MIN",
    "N_MAX",
    "N_AVG",
    "FC_MIN",
    "FC_MAX",
    "FC_AVG",
    "TC_MIN",
    "TC_MAX",
    "TC_AVG",
]

In [143]:
def process(file_name, *args):
    table = pd.concat(args, axis=0)
    table.columns = cols
    table.reset_index(inplace=True, drop=True)
    table.to_pickle(f"./{file_name}.pkl")
    return table


def preprocess(x, i, j, row_drop, col_drop):
    x = (
        (
            x.drop(axis=0, index=range(i))
            .replace("BDL", 0)
            .replace("_", np.nan)
            .replace("-", np.nan)
        )
        .iloc[:, :j]
        .drop(axis=0, index=row_drop)
        .drop(axis=1, columns=col_drop)
    )
    x.columns = range(19)
    return x


def table(
    excel_name, sheet_name, skip_header, skip_last_cols, row_drop=[], col_drop=[]
):
    return list(
        map(
            lambda i, x: preprocess(
                x,
                skip_header[i],
                skip_last_cols[i],
                row_drop[i] if len(row_drop) > 0 else [],
                col_drop[i] if len(col_drop) > 0 else [],
            ),
            range(len(sheet_name)),
            list(
                pd.read_excel(excel_name, sheet_name=sheet_name, header=None).values()
            ),
        )
    )

In [147]:
file_name = "YAMUNA".upper()
year = 2013
excel_name = f"data/xls/WQ {year}.xlsx"

locs = [5, 8, 11, 14, 17, 20, 23, 26]

a = (
    (
        list(pd.read_excel(excel_name, sheet_name=[9], header=None).values())[0]
        .drop(axis=0, index=range(4))
        .iloc[:, :]
    )
    .replace("BDL", 0)
    .replace("_", np.nan)
    .replace("-", np.nan)
)
# a.columns = range(19)
# i = 3
# for x in locs:
#     a.insert(loc=x, column=cols[x], value=(t_[i] + t_[i + 1]) / 2)
#     i += 2
# a.columns = cols
# a["CODE"] = a["CODE"].replace(
#     "PRIMARY WATER  QUALITY CRITERIA NOTIFIED\nUNDER E(P) RULES, 1986", " "
# )
# drop_row = a.query("CODE == ' '").index
# a.drop(axis=0, index=drop_row, inplace=True)
# a["CODE"].unique()
# process(f"data/pkl/{file_name}_{year}", a)
a.columns = cols
a.reset_index(inplace=True, drop=True)
a.to_csv(f"./data/csv/{file_name}_{year}.csv", index=False)
# pd.read_pickle(f"data/pkl/{file_name}_{year}.pkl")
pd.read_csv(f"data/csv/{file_name}_{year}.csv")
# t = table(excel_name, [5], [4, 3, 3], [-3,-2])
# for t_ in t:
#     i = 3
#     for x in locs:
#         t_.insert(loc=x, column=cols[x], value=(t_[i] + t_[i + 1]) / 2)
#         i += 2
# pd.concat(t, axis=0)
# process(f"data/pkl/{file_name}_{year}", *t)
# pd.read_pickle(f"data/pkl/{file_name}_{year}.pkl")

,CODE,LOCATION,STATE,T_MIN,T_MAX,T_AVG,DO_MIN,DO_MAX,DO_AVG,PH_MIN,...,BOD_AVG,N_MIN,N_MAX,N_AVG,FC_MIN,FC_MAX,FC_AVG,TC_MIN,TC_MAX,TC_AVG
0,1492,"YAMUNA AT YAMUNOTRI, UTTAR PRADESH",UTTARAKHAND,2.8,3.0,2.86,7.9,8.4,8.2,7.8,...,NaN,0.00,0.00,0.00,220.0,220.0,220.0,220.0,220.0,220.0
1,1493,"YAMUNA AT HANUMANCHATTI, UTTAR PRADESH",UTTARAKHAND,8.0,13.2,10.60,7.1,8.8,8.0,8.2,...,NaN,0.00,0.00,0.00,18.0,18.0,18.0,33.0,33.0,33.0
2,1494,"YAMUNA AT U/S OF LAKHWAR DAM, U.P",UTTARAKHAND,12.2,23.0,19.60,5.2,8.8,7.4,7.8,...,1.9,0.00,0.00,0.00,7000.0,7000.0,7000.0,9400.0,9400.0,9400.0
3,1490,"YAMUNA AT U/S DAK PATTHAR, UTTAR PARDESH",UTTARAKHAND,12.8,23.2,19.10,6.0,8.4,7.3,7.8,...,2.0,0.00,0.00,0.00,180.0,35000.0,12293.0,21.0,35000.0,7512.0
4,1553,"YAMUNA , U/S PAONTA SAHIB, H.P",HIMACHAL PRADESH,13.0,28.0,19.50,6.2,24.0,8.9,7.0,...,1.1,0.22,1.66,1.15,4.0,16.0,10.0,12.0,29.0,21.0
5,1554,"YAMUNA , D/S PAONTA SAHIB, H.P",HIMACHAL PRADESH,14.0,29.0,20.40,6.0,27.0,9.0,6.6,...,3.6,0.26,1.05,1.00,3.0,15.0,10.0,10.0,28.0,21.0
6,1117,YAMUNA AT HATHNIKUND HARYANA,HARYANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1496,"YAMUNA AT KALANAUR, YAMUNA NAGAR, HARYANA",HARYANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1119,"YAMUNA AT SONEPAT, HARYANA",HARYANA,NaN,NaN,NaN,8.1,8.1,8.1,7.4,...,1.6,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
9,1120,"YAMUNA AT WAZIRABAD, DELHI, CPCB",DELHI,NaN,NaN,NaN,9.5,11.5,10.5,7.7,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1700.0,3300.0,2500.0
10,1121,"YAMUNA AT NIZAMUDDIN, DELHI",DELHI,NaN,NaN,NaN,0.6,0.6,0.6,7.3,...,14.0,12.50,12.50,12.50,NaN,NaN,NaN,9200000.0,9200000.0,9200000.0
11,1375,"YAMUNA AT OKHLA BRIDGE (INLET OF AGRA CANAL), ...",DELHI,NaN,NaN,NaN,0.7,0.7,0.7,7.4,...,17.0,19.30,19.30,19.30,NaN,NaN,NaN,2200000.0,3500000.0,2850000.0
12,1812,YAMUNA AT OKHLA AFTER MEETING OF SHAHDARA DRAI...,DELHI,NaN,NaN,NaN,0.6,0.7,0.6,7.3,...,31.0,NaN,NaN,NaN,NaN,NaN,NaN,3500000.0,9200000.0,6350000.0
13,1497,"YAMUNA AT MAZAWALI, U.P",UTTAR PRADESH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2495,"YAMUNA AT KESIGHAT, VRINDAVAN",UTTAR PRADESH,22.0,30.0,26.60,4.0,6.8,5.7,7.2,...,7.0,0.00,0.00,0.00,28000.0,41000.0,35200.0,63000.0,70000.0,66600.0
15,1123,"YAMUNA AT MATHURA U/S , U.P.",DELHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2494,"YAMUNA AT VISHRAMGHAT, MATHURA",UTTAR PRADESH,20.0,30.0,26.20,3.6,6.4,5.5,7.3,...,7.8,0.00,0.00,0.00,37000.0,48000.0,42600.0,79000.0,94000.0,87200.0
17,1124,"YAMUNA AT MATHURA D/S , U.P.",DELHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1125,"YAMUNA AT AGRA U/S, U.P.",UTTAR PRADESH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1126,"YAMUNA AT D/S OF AGRA, U.P.",UTTAR PRADESH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2493,YAMUNA AT SHAHPUR,UTTAR PRADESH,20.0,30.0,26.20,3.8,7.6,6.1,7.2,...,5.7,0.00,0.00,0.00,24000.0,28000.0,26200.0,43000.0,54000.0,47800.0
21,1498,"YAMUNA AT BATESWAR, U.P","CPCB, DELHI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1127,"YAMUNA AT ETAWAH, U.P.","CPCB, DELHI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1499,"YAMUNA AT JUHIKA B/C WITH CHANBAL, ETAWAH, U.P","CPCB, DELHI",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2283,YAMUNA AT HAMIRPUR,UTTAR PRADESH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1069,"YAMUNA AT ALLAHABAD D/S (BALUA GHAT), U.P",UTTAR PRADESH,19.8,29.9,24.70,NaN,NaN,NaN,7.9,...,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
import os
from pathlib import Path

import numpy as np

data_path = Path("data/pkl/")
files = list(
    map(lambda x: x.name.replace(".pkl", "").split("_"), data_path.glob("*.pkl"))
)
river2year = {}
year2river = {}
for file in files:
    if file[0] in river2year:
        river2year[file[0]].append(int(file[1]))
    else:
        river2year[file[0]] = [int(file[1])]
    if int(file[1]) in year2river:
        year2river[int(file[1])].append(file[0])
    else:
        year2river[int(file[1])] = [file[0]]

df = pd.DataFrame(columns=river2year.keys(), index=range(2012, 2022))
for river in river2year.keys():
    df[river] = list(map(lambda x: river2year[river].count(x), list(df[river].index)))

In [152]:
for y in range(2013, 2014):
    paths = {k: Path(f"data/pkl/{k}_{y}.pkl") for k in year2river[y]}
    df_y = pd.DataFrame()
    for river, path in paths.items():
        df = pd.read_pickle(path)
        df["RIVER"] = river
        df = df[["RIVER", *df.columns[:-1]]]
        df_y = pd.concat([df_y, df], axis=0)
    df_y.to_csv(f"data/csv/{y}.csv", index=False)

In [814]:
csv_files = list(Path("data/csv").glob("*.csv"))
# for file in csv_files:
#
curr = 5
a = pd.read_csv(csv_files[curr])
# a = a.drop(axis=0, index=84)
# # a.loc[203,'CODE'] = 1323
# a['CODE'] = a['CODE'].astype(int)
# a.dtypes
# a["CODE"] = a["CODE"].replace(
#     'PRIMARY WATER  QUALITY CRITERIA\nNOTIFIED UNDER E(P) RULES, 1986', " "
# )
# drop_row = a.query("CODE == ' '").index
# a.drop(axis=0, index=drop_row, inplace=True)
# a = a.replace("BDL", 0).replace("_", np.nan).replace("-", np.nan)
for i in range(5, 27, 3):
    a[cols[i]] = (a[cols[i - 2]] + a[cols[i - 1]]) / 2
a.query("CODE == 1690")
# a.loc[[96,97],'TC_MAX'] = 1600000
# a.query("CODE == 30006")
a.to_csv(csv_files[curr], index=False)

In [168]:
from pathlib import Path

csv_files = list(Path("data/csv").glob("*.csv"))
df = pd.DataFrame()
for file in csv_files:
    df_ = pd.read_csv(file)
    df_["YEAR"] = file.name.replace(".csv", "")
    df_ = df_[["YEAR", *df_.columns[:-1]]]
    df = pd.concat([df, df_], axis=0)
df.to_csv("WQ 2012_2021.csv", index=False)

In [167]:
def df_cols(year):
    return (
        pd.read_csv(f"data/csv/{year}.csv")
        .replace("UTTAR\nPRADESH", "UTTAR PRADESH")
        .replace("HIMACHAL\nPRADESH", "HIMACHAL PRADESH")
        .replace("ANDHRA\nPRADESH", "ANDHRA PRADESH")
        .replace("TAMIL\nNADU", "TAMIL NADU")
        .replace("TAMILNADU", "TAMIL NADU")
        .replace("UTTARAKH\nAND", "UTTARAKHAND")
        .replace("UTTARAKH AND", "UTTARAKHAND")
        .replace("ANDHRA", "ANDHRA PRADESH")
        .replace("CPCB, DELHI", "DELHI")
        .replace("ORISSA", "ODISHA")
        .replace("UTTRAKHAND", "UTTARAKHAND")
        .replace("CHATTISGARH", "CHHATTISGARH")
    )
    

year = 2012
# df.loc[[171], 'STATE'] = 'MAHARASHTRA'
# df = df_cols(2015)
# print(df["STATE"].unique())
# df = df_cols(2013)
# print(df["STATE"].unique())
df = df_cols(year)
print(df["STATE"].unique())
df.to_csv(f"data/csv/{year}.csv", index=False)

# df.to_csv(f"data/csv/{year}.csv", index=False)

['UTTARAKHAND' 'HIMACHAL PRADESH' 'HARYANA' 'DELHI' 'UTTAR PRADESH'
 'PUNJAB' 'BIHAR' 'WEST BENGAL' 'ASSAM' 'CHHATTISGARH' 'ODISHA'
 'MAHARASHTRA' 'ANDHRA PRADESH' 'KARNATAKA' 'TAMIL NADU']

In [14]:
import pandas as pd

original = pd.read_csv("./WQ 2012_2021.csv").shape[0]
dropped = pd.read_csv("./WQ 2012_2021.csv").dropna().shape[0]

print(f"Original: {original}\nDropped: {dropped}")

Original: 2926
Dropped: 2350